version: '3.9'

services:
  searchtex-api:
    build:
      context: .
    container_name: searchtex-api
    ports:
      - "5000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@pgvector-db:5432/postgres
      - LLM_MODEL_NAME=llama3.2
      - LLM_URL=http://host.docker.internal:11434
    depends_on:
      - pgvector-db
    restart: unless-stopped

  pgvector-db:
    image: ankane/pgvector
    container_name: pgvector-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  pgvector_data:
